### ISSUE TITLE
题目分页查询存在一些缺陷

### ISSUE THREAD

**Issue by 41275199** [ifyun/Cloud-OJ#40]
复现步骤:
 1.切换到第三页
 2.搜索"萌新专题"
此时page应该重置为1

![image](https://github.com/ifyun/Cloud-OJ/assets/57012490/7e826c72-e20d-48fe-8abb-d2c84fb1b285)

**Comment by ifyun** [comment]
已修复 [db2cd1e](https://github.com/ifyun/Cloud-OJ/commit/db2cd1e09582ae36c73e89a4b9290a7d2e9baa63)

**Comment by 41275199** [comment]
目前好像还是存在问题，当我在page3的时候点击萌新专题，依然搜索不到结果
![image](https://github.com/ifyun/Cloud-OJ/assets/57012490/8680ba19-77bd-4f4c-865b-b07fbe59fee5)
